
SELECT '### DROP TABLES ###' AS ' ';

source drop_tables.sql

SELECT '### CREATE TABLES ###' AS ' ';

source create_tables_ansi.sql

SELECT '### IMPORT AUTHORITY CODE DATA ###' AS ' ';

LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv.psv'           INTO TABLE ADDRESS_ALIAS_TYPE_AUT         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_TYPE_AUT_psv.psv'                 INTO TABLE ADDRESS_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_FLAT_TYPE_AUT_psv.psv'                    INTO TABLE FLAT_TYPE_AUT                  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_RELIABILITY_AUT_psv.psv'          INTO TABLE GEOCODE_RELIABILITY_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_TYPE_AUT_psv.psv'                 INTO TABLE GEOCODE_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv.psv'          INTO TABLE GEOCODED_LEVEL_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LEVEL_TYPE_AUT_psv.psv'                   INTO TABLE LEVEL_TYPE_AUT                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv.psv'          INTO TABLE LOCALITY_ALIAS_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_CLASS_AUT_psv.psv'               INTO TABLE LOCALITY_CLASS_AUT             FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_MB_MATCH_CODE_AUT_psv.psv'                INTO TABLE MB_MATCH_CODE_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_PS_JOIN_TYPE_AUT_psv.psv'                 INTO TABLE PS_JOIN_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_CLASS_AUT_psv.psv'                 INTO TABLE STREET_CLASS_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_TYPE_AUT_psv.psv'                  INTO TABLE STREET_TYPE_AUT                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS_TYPE_AUT FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_SUFFIX_AUT_psv.psv'                INTO TABLE STREET_SUFFIX_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT '### CREATE TABLE RELATIONSHIPS ###' AS ' ';

source add_fk_constraints.sql

SELECT '### CREATE VIEWS ###' AS ' ';

source address_view.sql

