
SELECT sysdate || ' ### DROP TABLES ###' AS ' ';

source drop_tables.sql

SELECT sysdate || ' ### CREATE TABLES ###' AS ' ';

source create_tables_ansi.sql

SELECT sysdate || ' ### IMPORT AUTHORITY CODE DATA ###' AS ' ';

LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv.psv'           INTO TABLE ADDRESS_ALIAS_TYPE_AUT         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_TYPE_AUT_psv.psv'                 INTO TABLE ADDRESS_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_FLAT_TYPE_AUT_psv.psv'                    INTO TABLE FLAT_TYPE_AUT                  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_RELIABILITY_AUT_psv.psv'          INTO TABLE GEOCODE_RELIABILITY_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_TYPE_AUT_psv.psv'                 INTO TABLE GEOCODE_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv.psv'          INTO TABLE GEOCODED_LEVEL_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LEVEL_TYPE_AUT_psv.psv'                   INTO TABLE LEVEL_TYPE_AUT                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv.psv'          INTO TABLE LOCALITY_ALIAS_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_CLASS_AUT_psv.psv'               INTO TABLE LOCALITY_CLASS_AUT             FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_MB_MATCH_CODE_AUT_psv.psv'                INTO TABLE MB_MATCH_CODE_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_PS_JOIN_TYPE_AUT_psv.psv'                 INTO TABLE PS_JOIN_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_CLASS_AUT_psv.psv'                 INTO TABLE STREET_CLASS_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_TYPE_AUT_psv.psv'                  INTO TABLE STREET_TYPE_AUT                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS_TYPE_AUT FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_SUFFIX_AUT_psv.psv'                INTO TABLE STREET_SUFFIX_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT sysdate || ' ### IMPORT WA DATA ###' AS ' ';

LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_MESH_BLOCK_2011_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2011 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_MB_2011_psv.psv'                 INTO TABLE MB_2011                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;


SELECT sysdate || ' ### CREATE TABLE RELATIONSHIPS ###' AS ' ';

source add_fk_constraints.sql

SELECT sysdate || ' ### CREATE VIEWS ###' AS ' ';

source address_view.sql

