-- ********************************************************************************************
-- ********************************************************************************************
--  DROP TABLE IF EXISTSs in correct parent/ foreign key order (children before parents) 
-- ********************************************************************************************
-- ********************************************************************************************

 DROP TABLE IF EXISTS STREET_LOCALITY_POINT;
 DROP TABLE IF EXISTS PRIMARY_SECONDARY;
 DROP TABLE IF EXISTS ADDRESS_MESH_BLOCK_2016;
 DROP TABLE IF EXISTS ADDRESS_SITE_GEOCODE;
 DROP TABLE IF EXISTS LOCALITY_ALIAS;
 DROP TABLE IF EXISTS LOCALITY_POINT;
 DROP TABLE IF EXISTS ADDRESS_MESH_BLOCK_2011;
 DROP TABLE IF EXISTS ADDRESS_ALIAS;
 DROP TABLE IF EXISTS LOCALITY_NEIGHBOUR;
 DROP TABLE IF EXISTS ADDRESS_DEFAULT_GEOCODE;
 DROP TABLE IF EXISTS STREET_LOCALITY_ALIAS;
 DROP TABLE IF EXISTS MB_2016;
 DROP TABLE IF EXISTS ADDRESS_DETAIL;
 DROP TABLE IF EXISTS MB_MATCH_CODE_AUT;
 DROP TABLE IF EXISTS MB_2011;
 DROP TABLE IF EXISTS STREET_LOCALITY_ALIAS_TYPE_AUT;
 DROP TABLE IF EXISTS LOCALITY_ALIAS_TYPE_AUT;
 DROP TABLE IF EXISTS GEOCODE_TYPE_AUT;
 DROP TABLE IF EXISTS ADDRESS_ALIAS_TYPE_AUT;
 DROP TABLE IF EXISTS PS_JOIN_TYPE_AUT;
 DROP TABLE IF EXISTS GEOCODED_LEVEL_TYPE_AUT;
 DROP TABLE IF EXISTS STREET_LOCALITY;
 DROP TABLE IF EXISTS ADDRESS_SITE;
 DROP TABLE IF EXISTS LEVEL_TYPE_AUT;
 DROP TABLE IF EXISTS FLAT_TYPE_AUT;
 DROP TABLE IF EXISTS STREET_TYPE_AUT;
 DROP TABLE IF EXISTS LOCALITY;
 DROP TABLE IF EXISTS STREET_CLASS_AUT;
 DROP TABLE IF EXISTS STREET_SUFFIX_AUT;
 DROP TABLE IF EXISTS ADDRESS_TYPE_AUT;
 DROP TABLE IF EXISTS LOCALITY_CLASS_AUT;
 DROP TABLE IF EXISTS STATE;
 DROP TABLE IF EXISTS GEOCODE_RELIABILITY_AUT;
